## Load data

```{r Load Data}
library(tidyverse)

filenames <- str_replace(list.files(pattern = "*.csv"), ".csv", "")


datas <- tibble()

for (name in filenames) {
    datas <- read_csv(paste0(name, ".csv")) %>%
        mutate(lockname = name) %>%
        add_row(datas)
}

datas <- datas %>%
    mutate(cpu = as.integer(str_extract(lockname, "[0-9]+"))) %>%
    mutate(locktype = `lock type`)
```


```{r}

datas %>%
    group_by(`locktype`, `cpu`) %>%
    summarise(iteration = sum(loop), lockname = lockname) %>%
    ggplot() +
    geom_point(aes(
        x = reorder(lockname, cpu),
        y = iteration, group = `locktype`
    )) +
    facet_grid(~locktype, scale = "free") +
    theme(axis.text.x = element_text(angle = 60, hjust = 1, vjust = 0.5)) +
    ggtitle("Number of overall iterations")
```

```{r}
datas %>%
    ggplot() +
    geom_histogram(aes(x = loop, fill = locktype), bins = 15) +
    facet_wrap(~cpu, scale = "free") +
    ggtitle("distribution of loop counts")
```

```{r}
# graph the distribution of lock_acquires

datas %>%
    ggplot() +
    geom_histogram(aes(x = lock_acquires, fill = locktype), bins = 15) +
    facet_wrap(~cpu, scale = "free") +
    ggtitle("disbution of number of lock acquires")
```

```{r}
```